In [156]:
# Referenced code from https://www.youtube.com/watch?v=aZsZrkIgan0
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier

In [157]:
data = pd.read_csv("train.csv").as_matrix()

In [158]:
print(data)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [7 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]]


In [159]:
clf = DecisionTreeClassifier()

In [168]:
xtrain = data[0:21000, 1:]

In [169]:
train_label = data[0:21000, 0]

In [170]:
clf.fit(xtrain, train_label)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [176]:
xtest=data[21000:, 1:]

In [181]:
actual_label = data[21000:, 0]

In [182]:
#d = xtest[8]

In [183]:
prediction = clf.predict(xtest)

In [185]:
count = 0
for i in range(0, 21000):
    count += 1 if prediction[i] == actual_label[i] else 0
print("Accuracy = ", (count / 21000) * 100)

Accuracy =  83.67142857142858


In [186]:
results = pd.Series(prediction,name="Label")
submission = pd.concat([pd.Series(range(1,28001), name = "ImageId"), results], axis = 1)
submission.to_csv("kaggle.csv",index=False)